import type { CompanyLink, CompanyNarrative, CompanyNode, MatrixLayer } from "@/lib/company-matrix/types";

export const NARRATIVE_LABELS: Record<CompanyNarrative, string> = {
  "ai-agents": "AI Agents",
  "energy-reconstruction": "Energy Reconstruction",
  "defense-autonomy": "Defense Autonomy",
  "space-infrastructure": "Space Infrastructure",
  "automated-production": "Automated Production",
  "financial-data-intelligence": "Financial / Data Intelligence"
};

export const COMPANY_MATRIX_LAYERS: MatrixLayer[] = [
  { id: 1, label: "Future Narratives", summary: "Outcome layer: where the market narrative becomes visible." },
  { id: 2, label: "Application Layer", summary: "Companies that package future narratives into products and platforms." },
  { id: 3, label: "Software / Data / Cloud Layer", summary: "Data, workflow, cloud, security, and enterprise software substrate." },
  { id: 4, label: "Compute Layer", summary: "GPU, networking, memory, servers, and silicon infrastructure." },
  { id: 5, label: "Manufacturing / Equipment / Design Layer", summary: "Foundry, lithography, EDA, and semiconductor equipment." },
  { id: 6, label: "Energy / Materials / Physical Infrastructure Layer", summary: "Power, grid, uranium, copper, and physical bottlenecks." },
  { id: 7, label: "Capital / Defense / Geopolitical Constraint Layer", summary: "Capital markets, defense, industrial cycle, and policy constraints." }
];

export const COMPANY_NODES: CompanyNode[] = [
  { ticker: "MSFT", name: "Microsoft", primaryLayer: 2, secondaryLayers: [3, 4], narratives: ["ai-agents", "financial-data-intelligence"], role: "core dependency", thesis: "Owns enterprise distribution, cloud demand, and AI workflow packaging." },
  { ticker: "GOOGL", name: "Alphabet", primaryLayer: 2, secondaryLayers: [3, 4], narratives: ["ai-agents", "financial-data-intelligence"], role: "core dependency", thesis: "Combines search distribution, Gemini, cloud, and internal silicon demand." },
  { ticker: "META", name: "Meta Platforms", primaryLayer: 2, secondaryLayers: [4], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Turns AI infrastructure into advertising, engagement, and creator tooling leverage." },
  { ticker: "AMZN", name: "Amazon", primaryLayer: 2, secondaryLayers: [3, 4], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "AWS and logistics make Amazon both compute buyer and automation operator." },
  { ticker: "TSLA", name: "Tesla", primaryLayer: 2, secondaryLayers: [6], narratives: ["automated-production", "energy-reconstruction"], role: "narrative spillover", thesis: "Sits across EVs, autonomy, batteries, robotics, and energy storage." },
  { ticker: "PLTR", name: "Palantir", primaryLayer: 2, secondaryLayers: [3, 7], narratives: ["defense-autonomy", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Packages operational data into defense, enterprise, and AI workflow decisions." },
  { ticker: "APP", name: "AppLovin", primaryLayer: 2, secondaryLayers: [3], narratives: ["ai-agents", "financial-data-intelligence"], role: "narrative spillover", thesis: "Shows how AI optimization can turn data loops into high-margin application economics." },
  { ticker: "NOW", name: "ServiceNow", primaryLayer: 2, secondaryLayers: [3], narratives: ["ai-agents", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Enterprise workflow layer where agents can become operational tools." },
  { ticker: "SNOW", name: "Snowflake", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence", "ai-agents"], role: "second-order beneficiary", thesis: "Data cloud that benefits when enterprise data becomes AI-ready." },
  { ticker: "CRM", name: "Salesforce", primaryLayer: 3, secondaryLayers: [2], narratives: ["ai-agents", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Customer workflow and data layer for enterprise AI features." },
  { ticker: "ORCL", name: "Oracle", primaryLayer: 3, secondaryLayers: [4], narratives: ["ai-agents"], role: "core dependency", thesis: "Database and cloud capacity increasingly tied to AI infrastructure demand." },
  { ticker: "MDB", name: "MongoDB", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "second-order beneficiary", thesis: "Application database layer for software teams building data-heavy products." },
  { ticker: "DDOG", name: "Datadog", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "constraint variable", thesis: "Observability spend tracks cloud complexity and AI operations pressure." },
  { ticker: "NET", name: "Cloudflare", primaryLayer: 3, secondaryLayers: [4], narratives: ["ai-agents", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Edge network and security layer that can host inference and protect traffic." },
  { ticker: "CRWD", name: "CrowdStrike", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence", "defense-autonomy"], role: "constraint variable", thesis: "Security becomes a constraint as AI and automation expand attack surfaces." },
  { ticker: "PANW", name: "Palo Alto Networks", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence", "defense-autonomy"], role: "constraint variable", thesis: "Platform security provider tied to cloud, AI, and enterprise risk budgets." },
  { ticker: "NVDA", name: "NVIDIA", primaryLayer: 4, secondaryLayers: [2], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Primary compute bottleneck and accelerator ecosystem for AI demand." },
  { ticker: "AMD", name: "AMD", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Alternative accelerator and CPU supplier when compute demand broadens." },
  { ticker: "AVGO", name: "Broadcom", primaryLayer: 4, secondaryLayers: [3, 5], narratives: ["ai-agents", "financial-data-intelligence"], role: "core dependency", thesis: "Custom silicon, networking, and software cash flow meet AI infrastructure." },
  { ticker: "ANET", name: "Arista Networks", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "core dependency", thesis: "Data center networking bottleneck for cloud and AI clusters." },
  { ticker: "MRVL", name: "Marvell", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Custom silicon and connectivity supplier for hyperscale infrastructure." },
  { ticker: "SMCI", name: "Super Micro Computer", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "narrative spillover", thesis: "Server assembly proxy for AI rack demand and execution risk." },
  { ticker: "DELL", name: "Dell Technologies", primaryLayer: 4, secondaryLayers: [2], narratives: ["ai-agents", "automated-production"], role: "second-order beneficiary", thesis: "Enterprise server and AI infrastructure distribution channel." },
  { ticker: "MU", name: "Micron", primaryLayer: 4, secondaryLayers: [5], narratives: ["ai-agents"], role: "constraint variable", thesis: "Memory and HBM supply shape the economics of accelerator systems." },
  { ticker: "TSM", name: "Taiwan Semiconductor", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Foundry bottleneck for advanced chips and AI accelerators." },
  { ticker: "ASML", name: "ASML", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents"], role: "core dependency", thesis: "Lithography monopoly that constrains leading-edge chip supply." },
  { ticker: "AMAT", name: "Applied Materials", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Broad semiconductor equipment supplier for capacity expansion." },
  { ticker: "LRCX", name: "Lam Research", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Etch and deposition exposure to memory and logic capex." },
  { ticker: "KLAC", name: "KLA", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents"], role: "constraint variable", thesis: "Process control layer that protects yield at advanced nodes." },
  { ticker: "SNPS", name: "Synopsys", primaryLayer: 5, secondaryLayers: [3], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "EDA and IP tooling required for chip design complexity." },
  { ticker: "CDNS", name: "Cadence Design Systems", primaryLayer: 5, secondaryLayers: [3], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Chip and system design tooling for silicon and simulation workflows." },
  { ticker: "ARM", name: "Arm Holdings", primaryLayer: 5, secondaryLayers: [4], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Instruction-set and IP layer for efficient compute designs." },
  { ticker: "CEG", name: "Constellation Energy", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "ai-agents"], role: "constraint variable", thesis: "Nuclear power supply becomes a data center constraint and premium asset." },
  { ticker: "VST", name: "Vistra", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "ai-agents"], role: "constraint variable", thesis: "Power generation exposure to AI data center load growth." },
  { ticker: "CCJ", name: "Cameco", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "core dependency", thesis: "Uranium supply chain proxy for nuclear power rebuild." },
  { ticker: "ETN", name: "Eaton", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "automated-production"], role: "core dependency", thesis: "Electrical equipment supplier for grid, data center, and industrial electrification." },
  { ticker: "PWR", name: "Quanta Services", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "core dependency", thesis: "Grid construction and transmission bottleneck contractor." },
  { ticker: "GEV", name: "GE Vernova", primaryLayer: 6, secondaryLayers: [7], narratives: ["energy-reconstruction", "automated-production"], role: "constraint variable", thesis: "Power equipment and grid modernization exposure." },
  { ticker: "NEM", name: "Newmont", primaryLayer: 6, secondaryLayers: [7], narratives: ["energy-reconstruction"], role: "constraint variable", thesis: "Gold and resource hedge when capital and geopolitical stress rise." },
  { ticker: "FCX", name: "Freeport-McMoRan", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "automated-production"], role: "constraint variable", thesis: "Copper supply proxy for electrification and grid capex." },
  { ticker: "JPM", name: "JPMorgan Chase", primaryLayer: 7, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "constraint variable", thesis: "Capital availability and credit cycle shape all long-duration narratives." },
  { ticker: "GS", name: "Goldman Sachs", primaryLayer: 7, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "second-order beneficiary", thesis: "Capital markets and deal activity reflect narrative monetization." },
  { ticker: "LMT", name: "Lockheed Martin", primaryLayer: 7, secondaryLayers: [2], narratives: ["defense-autonomy", "space-infrastructure"], role: "core dependency", thesis: "Prime defense platform tied to missiles, space, and autonomy budgets." },
  { ticker: "RTX", name: "RTX", primaryLayer: 7, secondaryLayers: [], narratives: ["defense-autonomy", "space-infrastructure"], role: "core dependency", thesis: "Defense and aerospace supply chain exposure." },
  { ticker: "NOC", name: "Northrop Grumman", primaryLayer: 7, secondaryLayers: [], narratives: ["defense-autonomy", "space-infrastructure"], role: "core dependency", thesis: "Defense autonomy, aerospace, and strategic systems exposure." },
  { ticker: "BA", name: "Boeing", primaryLayer: 7, secondaryLayers: [], narratives: ["space-infrastructure", "defense-autonomy"], role: "constraint variable", thesis: "Aerospace industrial execution risk and defense backlog proxy." },
  { ticker: "CAT", name: "Caterpillar", primaryLayer: 7, secondaryLayers: [6], narratives: ["automated-production", "energy-reconstruction"], role: "constraint variable", thesis: "Heavy equipment cycle tied to infrastructure, mining, and capex." },
  { ticker: "XOM", name: "Exxon Mobil", primaryLayer: 7, secondaryLayers: [6], narratives: ["energy-reconstruction"], role: "constraint variable", thesis: "Hydrocarbon cash flow hedge during energy transition volatility." }
];

export const COMPANY_LINKS: CompanyLink[] = [
  { source: "MSFT", target: "NVDA", strength: "core", role: "depends_on", thesis: "Azure AI demand depends on accelerator supply." },
  { source: "GOOGL", target: "AVGO", strength: "strong", role: "depends_on", thesis: "Custom silicon and networking relationship for AI infrastructure." },
  { source: "AMZN", target: "ANET", strength: "strong", role: "depends_on", thesis: "AWS scale needs high-performance data center networking." },
  { source: "META", target: "NVDA", strength: "strong", role: "depends_on", thesis: "Model training and recommendation systems drive GPU demand." },
  { source: "NVDA", target: "TSM", strength: "core", role: "depends_on", thesis: "Accelerators require advanced foundry capacity." },
  { source: "AMD", target: "TSM", strength: "core", role: "depends_on", thesis: "Advanced CPUs and GPUs rely on external foundry capacity." },
  { source: "TSM", target: "ASML", strength: "core", role: "depends_on", thesis: "Leading-edge nodes require EUV lithography." },
  { source: "TSM", target: "AMAT", strength: "strong", role: "depends_on", thesis: "Capacity expansion needs broad equipment supply." },
  { source: "MU", target: "LRCX", strength: "strong", role: "depends_on", thesis: "HBM and memory cycles pull etch and deposition demand." },
  { source: "AVGO", target: "SNPS", strength: "strong", role: "depends_on", thesis: "Custom silicon complexity depends on EDA tooling." },
  { source: "NVDA", target: "SNPS", strength: "strong", role: "depends_on", thesis: "Chip design scale relies on EDA and verification." },
  { source: "ARM", target: "TSM", strength: "weak", role: "enables", thesis: "Efficient IP connects chip design to advanced manufacturing." },
  { source: "ANET", target: "AVGO", strength: "strong", role: "supplies", thesis: "Networking stacks combine switching systems and merchant silicon." },
  { source: "SMCI", target: "NVDA", strength: "core", role: "depends_on", thesis: "Server demand is levered to available accelerator supply." },
  { source: "DELL", target: "NVDA", strength: "strong", role: "depends_on", thesis: "Enterprise AI servers need GPU supply and reference designs." },
  { source: "ORCL", target: "NVDA", strength: "strong", role: "depends_on", thesis: "Cloud AI capacity turns GPU access into growth." },
  { source: "SNOW", target: "MSFT", strength: "weak", role: "depends_on", thesis: "Enterprise data workloads are distributed through cloud partnerships." },
  { source: "CRM", target: "SNOW", strength: "weak", role: "enables", thesis: "Customer workflows become stronger when linked to data clouds." },
  { source: "NOW", target: "MSFT", strength: "weak", role: "enables", thesis: "Enterprise agent workflows meet Microsoft distribution." },
  { source: "PLTR", target: "LMT", strength: "strong", role: "enables", thesis: "Defense software and prime systems converge around autonomy." },
  { source: "CRWD", target: "PANW", strength: "weak", role: "competes_with", thesis: "Security budgets rotate between endpoint, cloud, and platform approaches." },
  { source: "NET", target: "CRWD", strength: "weak", role: "enables", thesis: "Edge traffic and security telemetry expand the security surface." },
  { source: "CEG", target: "NVDA", strength: "strong", role: "constrains", thesis: "Data center growth runs into power availability." },
  { source: "VST", target: "AMZN", strength: "strong", role: "constrains", thesis: "Hyperscale growth depends on dispatchable power." },
  { source: "ETN", target: "CEG", strength: "strong", role: "enables", thesis: "Electrical equipment connects generation to data center load." },
  { source: "PWR", target: "ETN", strength: "strong", role: "enables", thesis: "Grid construction converts equipment demand into deployed capacity." },
  { source: "CCJ", target: "CEG", strength: "strong", role: "supplies", thesis: "Uranium supply underpins nuclear generation economics." },
  { source: "FCX", target: "ETN", strength: "weak", role: "supplies", thesis: "Copper availability matters for electrification and grid equipment." },
  { source: "GEV", target: "PWR", strength: "weak", role: "enables", thesis: "Grid hardware and construction reinforce the same power rebuild cycle." },
  { source: "JPM", target: "TSLA", strength: "weak", role: "finances", thesis: "Credit and capital markets influence long-duration industrial narratives." },
  { source: "GS", target: "APP", strength: "weak", role: "finances", thesis: "Capital market appetite can amplify software narrative multiples." },
  { source: "LMT", target: "NOC", strength: "strong", role: "enables", thesis: "Prime defense systems overlap in space, missiles, and autonomy." },
  { source: "RTX", target: "BA", strength: "strong", role: "supplies", thesis: "Aerospace and defense supply chains remain tightly coupled." },
  { source: "NOC", target: "PLTR", strength: "strong", role: "depends_on", thesis: "Autonomous defense systems increasingly depend on operational software." },
  { source: "CAT", target: "FCX", strength: "weak", role: "enables", thesis: "Mining and heavy equipment cycles reinforce materials supply." },
  { source: "XOM", target: "TSLA", strength: "weak", role: "hedges", thesis: "Hydrocarbon cash flows hedge energy transition volatility." },
  { source: "NEM", target: "JPM", strength: "weak", role: "hedges", thesis: "Gold can hedge capital stress and currency uncertainty." }
];
