import type { CompanyLink, CompanyNarrative, CompanyNode, MatrixLayer } from "@/lib/company-matrix/types";

export const NARRATIVE_LABELS: Record<CompanyNarrative, string> = {
  "ai-agents": "AI Agents",
  "energy-reconstruction": "Energy Reconstruction",
  "defense-autonomy": "Defense Autonomy",
  "space-infrastructure": "Space Infrastructure",
  "automated-production": "Automated Production",
  "financial-data-intelligence": "Financial / Data Intelligence"
};

export const COMPANY_MATRIX_LAYERS: MatrixLayer[] = [
  { id: 1, label: "Future Narratives", summary: "Outcome layer: where the market narrative becomes visible." },
  { id: 2, label: "Application Layer", summary: "Companies that package future narratives into products and platforms." },
  { id: 3, label: "Software / Data / Cloud Layer", summary: "Data, workflow, cloud, security, and enterprise software substrate." },
  { id: 4, label: "Compute Layer", summary: "GPU, networking, memory, servers, and silicon infrastructure." },
  { id: 5, label: "Manufacturing / Equipment / Design Layer", summary: "Foundry, lithography, EDA, and semiconductor equipment." },
  { id: 6, label: "Energy / Materials / Physical Infrastructure Layer", summary: "Power, grid, uranium, copper, and physical bottlenecks." },
  { id: 7, label: "Capital / Defense / Geopolitical Constraint Layer", summary: "Capital markets, defense, industrial cycle, and policy constraints." }
];

export const COMPANY_NODES: CompanyNode[] = [
  { ticker: "MSFT", name: "Microsoft", nameZh: "微软", primaryLayer: 2, secondaryLayers: [3, 4], narratives: ["ai-agents", "financial-data-intelligence"], role: "core dependency", thesis: "Owns enterprise distribution, cloud demand, and AI workflow packaging." },
  { ticker: "GOOGL", name: "Alphabet", nameZh: "谷歌", primaryLayer: 2, secondaryLayers: [3, 4], narratives: ["ai-agents", "financial-data-intelligence"], role: "core dependency", thesis: "Combines search distribution, Gemini, cloud, and internal silicon demand." },
  { ticker: "META", name: "Meta Platforms", nameZh: "Meta 脸书", primaryLayer: 2, secondaryLayers: [4], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Turns AI infrastructure into advertising, engagement, and creator tooling leverage." },
  { ticker: "AMZN", name: "Amazon", nameZh: "亚马逊", primaryLayer: 2, secondaryLayers: [3, 4], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "AWS and logistics make Amazon both compute buyer and automation operator." },
  { ticker: "TSLA", name: "Tesla", nameZh: "特斯拉", primaryLayer: 2, secondaryLayers: [6], narratives: ["automated-production", "energy-reconstruction"], role: "narrative spillover", thesis: "Sits across EVs, autonomy, batteries, robotics, and energy storage." },
  { ticker: "PLTR", name: "Palantir", nameZh: "Palantir 帕兰提尔", primaryLayer: 2, secondaryLayers: [3, 7], narratives: ["defense-autonomy", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Packages operational data into defense, enterprise, and AI workflow decisions." },
  { ticker: "APP", name: "AppLovin", nameZh: "AppLovin", primaryLayer: 2, secondaryLayers: [3], narratives: ["ai-agents", "financial-data-intelligence"], role: "narrative spillover", thesis: "Shows how AI optimization can turn data loops into high-margin application economics." },
  { ticker: "NOW", name: "ServiceNow", nameZh: "ServiceNow", primaryLayer: 2, secondaryLayers: [3], narratives: ["ai-agents", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Enterprise workflow layer where agents can become operational tools." },
  { ticker: "SNOW", name: "Snowflake", nameZh: "Snowflake 雪花", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence", "ai-agents"], role: "second-order beneficiary", thesis: "Data cloud that benefits when enterprise data becomes AI-ready." },
  { ticker: "CRM", name: "Salesforce", nameZh: "Salesforce 赛富时", primaryLayer: 3, secondaryLayers: [2], narratives: ["ai-agents", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Customer workflow and data layer for enterprise AI features." },
  { ticker: "ORCL", name: "Oracle", nameZh: "甲骨文", primaryLayer: 3, secondaryLayers: [4], narratives: ["ai-agents"], role: "core dependency", thesis: "Database and cloud capacity increasingly tied to AI infrastructure demand." },
  { ticker: "MDB", name: "MongoDB", nameZh: "MongoDB", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "second-order beneficiary", thesis: "Application database layer for software teams building data-heavy products." },
  { ticker: "DDOG", name: "Datadog", nameZh: "Datadog", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "constraint variable", thesis: "Observability spend tracks cloud complexity and AI operations pressure." },
  { ticker: "NET", name: "Cloudflare", nameZh: "Cloudflare 云闪", primaryLayer: 3, secondaryLayers: [4], narratives: ["ai-agents", "financial-data-intelligence"], role: "second-order beneficiary", thesis: "Edge network and security layer that can host inference and protect traffic." },
  { ticker: "CRWD", name: "CrowdStrike", nameZh: "CrowdStrike 群胜", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence", "defense-autonomy"], role: "constraint variable", thesis: "Security becomes a constraint as AI and automation expand attack surfaces." },
  { ticker: "PANW", name: "Palo Alto Networks", nameZh: "Palo Alto Networks 派拓", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence", "defense-autonomy"], role: "constraint variable", thesis: "Platform security provider tied to cloud, AI, and enterprise risk budgets." },
  { ticker: "NVDA", name: "NVIDIA", nameZh: "英伟达", primaryLayer: 4, secondaryLayers: [2], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Primary compute bottleneck and accelerator ecosystem for AI demand." },
  { ticker: "AMD", name: "AMD", nameZh: "AMD 超微", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Alternative accelerator and CPU supplier when compute demand broadens." },
  { ticker: "AVGO", name: "Broadcom", nameZh: "博通", primaryLayer: 4, secondaryLayers: [3, 5], narratives: ["ai-agents", "financial-data-intelligence"], role: "core dependency", thesis: "Custom silicon, networking, and software cash flow meet AI infrastructure." },
  { ticker: "ANET", name: "Arista Networks", nameZh: "Arista 阿瑞斯塔", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "core dependency", thesis: "Data center networking bottleneck for cloud and AI clusters." },
  { ticker: "MRVL", name: "Marvell", nameZh: "美满电子", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Custom silicon and connectivity supplier for hyperscale infrastructure." },
  { ticker: "SMCI", name: "Super Micro Computer", nameZh: "超微电脑", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "narrative spillover", thesis: "Server assembly proxy for AI rack demand and execution risk." },
  { ticker: "DELL", name: "Dell Technologies", nameZh: "戴尔", primaryLayer: 4, secondaryLayers: [2], narratives: ["ai-agents", "automated-production"], role: "second-order beneficiary", thesis: "Enterprise server and AI infrastructure distribution channel." },
  { ticker: "MU", name: "Micron", nameZh: "美光", primaryLayer: 4, secondaryLayers: [5], narratives: ["ai-agents"], role: "constraint variable", thesis: "Memory and HBM supply shape the economics of accelerator systems." },
  { ticker: "TSM", name: "Taiwan Semiconductor", nameZh: "台积电", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Foundry bottleneck for advanced chips and AI accelerators." },
  { ticker: "ASML", name: "ASML", nameZh: "阿斯麦", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents"], role: "core dependency", thesis: "Lithography monopoly that constrains leading-edge chip supply." },
  { ticker: "AMAT", name: "Applied Materials", nameZh: "应用材料", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Broad semiconductor equipment supplier for capacity expansion." },
  { ticker: "LRCX", name: "Lam Research", nameZh: "拉姆研究", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Etch and deposition exposure to memory and logic capex." },
  { ticker: "KLAC", name: "KLA", nameZh: "科磊", primaryLayer: 5, secondaryLayers: [], narratives: ["ai-agents"], role: "constraint variable", thesis: "Process control layer that protects yield at advanced nodes." },
  { ticker: "SNPS", name: "Synopsys", nameZh: "新思科技", primaryLayer: 5, secondaryLayers: [3], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "EDA and IP tooling required for chip design complexity." },
  { ticker: "CDNS", name: "Cadence Design Systems", nameZh: "楷登电子", primaryLayer: 5, secondaryLayers: [3], narratives: ["ai-agents", "automated-production"], role: "core dependency", thesis: "Chip and system design tooling for silicon and simulation workflows." },
  { ticker: "ARM", name: "Arm Holdings", nameZh: "Arm 控股", primaryLayer: 5, secondaryLayers: [4], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Instruction-set and IP layer for efficient compute designs." },
  { ticker: "CEG", name: "Constellation Energy", nameZh: "星座能源", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "ai-agents"], role: "constraint variable", thesis: "Nuclear power supply becomes a data center constraint and premium asset." },
  { ticker: "VST", name: "Vistra", nameZh: "维斯特拉", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "ai-agents"], role: "constraint variable", thesis: "Power generation exposure to AI data center load growth." },
  { ticker: "CCJ", name: "Cameco", nameZh: "卡梅科", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "core dependency", thesis: "Uranium supply chain proxy for nuclear power rebuild." },
  { ticker: "ETN", name: "Eaton", nameZh: "伊顿", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "automated-production"], role: "core dependency", thesis: "Electrical equipment supplier for grid, data center, and industrial electrification." },
  { ticker: "PWR", name: "Quanta Services", nameZh: "匡塔服务", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "core dependency", thesis: "Grid construction and transmission bottleneck contractor." },
  { ticker: "GEV", name: "GE Vernova", nameZh: "GE Vernova", primaryLayer: 6, secondaryLayers: [7], narratives: ["energy-reconstruction", "automated-production"], role: "constraint variable", thesis: "Power equipment and grid modernization exposure." },
  { ticker: "NEM", name: "Newmont", nameZh: "纽蒙特", primaryLayer: 6, secondaryLayers: [7], narratives: ["energy-reconstruction"], role: "constraint variable", thesis: "Gold and resource hedge when capital and geopolitical stress rise." },
  { ticker: "FCX", name: "Freeport-McMoRan", nameZh: "自由港麦克莫兰", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "automated-production"], role: "constraint variable", thesis: "Copper supply proxy for electrification and grid capex." },
  { ticker: "JPM", name: "JPMorgan Chase", nameZh: "摩根大通", primaryLayer: 7, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "constraint variable", thesis: "Capital availability and credit cycle shape all long-duration narratives." },
  { ticker: "GS", name: "Goldman Sachs", nameZh: "高盛", primaryLayer: 7, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "second-order beneficiary", thesis: "Capital markets and deal activity reflect narrative monetization." },
  { ticker: "LMT", name: "Lockheed Martin", nameZh: "洛克希德马丁", primaryLayer: 7, secondaryLayers: [2], narratives: ["defense-autonomy", "space-infrastructure"], role: "core dependency", thesis: "Prime defense platform tied to missiles, space, and autonomy budgets." },
  { ticker: "RTX", name: "RTX", nameZh: "雷神技术", primaryLayer: 7, secondaryLayers: [], narratives: ["defense-autonomy", "space-infrastructure"], role: "core dependency", thesis: "Defense and aerospace supply chain exposure." },
  { ticker: "NOC", name: "Northrop Grumman", nameZh: "诺斯洛普格鲁曼", primaryLayer: 7, secondaryLayers: [], narratives: ["defense-autonomy", "space-infrastructure"], role: "core dependency", thesis: "Defense autonomy, aerospace, and strategic systems exposure." },
  { ticker: "BA", name: "Boeing", nameZh: "波音", primaryLayer: 7, secondaryLayers: [], narratives: ["space-infrastructure", "defense-autonomy"], role: "constraint variable", thesis: "Aerospace industrial execution risk and defense backlog proxy." },
  { ticker: "CAT", name: "Caterpillar", nameZh: "卡特彼勒", primaryLayer: 7, secondaryLayers: [6], narratives: ["automated-production", "energy-reconstruction"], role: "constraint variable", thesis: "Heavy equipment cycle tied to infrastructure, mining, and capex." },
  { ticker: "XOM", name: "Exxon Mobil", nameZh: "埃克森美孚", primaryLayer: 7, secondaryLayers: [6], narratives: ["energy-reconstruction"], role: "constraint variable", thesis: "Hydrocarbon cash flow hedge during energy transition volatility." },
  // === ZERO 2076 Watchlist 扩展 ===
  // AI 算力 弹性
  { ticker: "CBRS", name: "Cerebras (占位)", nameZh: "Cerebras 大脑", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "narrative spillover", thesis: "晶圆级 AI 推理 ASIC, 等 IPO 节点; 推理替代路线弹性筹码。" },
  // AI 基础设施 / 电力
  { ticker: "VRT", name: "Vertiv", nameZh: "Vertiv 维谛技术", primaryLayer: 6, secondaryLayers: [4], narratives: ["energy-reconstruction", "ai-agents"], role: "core dependency", thesis: "数据中心电力分配与液冷热管理龙头, AI 机柜核心瓶颈。" },
  // 核能 (AI 能源约束)
  { ticker: "SMR", name: "NuScale Power", nameZh: "NuScale 核能", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "core dependency", thesis: "小型模块化核反应堆 (SMR) 龙头, 数据中心 24/7 电力新形态。" },
  { ticker: "OKLO", name: "Oklo", nameZh: "Oklo 奥克洛", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "narrative spillover", thesis: "先进核裂变范式赌注, Sam Altman 背书; 高弹性叙事。" },
  { ticker: "NNE", name: "Nano Nuclear Energy", nameZh: "Nano Nuclear", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "narrative spillover", thesis: "微堆移动核能弹性标的; 国防与边缘电力概念。" },
  // 商业航天
  { ticker: "RKLB", name: "Rocket Lab", nameZh: "火箭实验室", primaryLayer: 2, secondaryLayers: [7], narratives: ["space-infrastructure", "defense-autonomy"], role: "core dependency", thesis: "中小型火箭 Electron + 卫星制造垂直整合, 商业航天龙头。" },
  { ticker: "ASTS", name: "AST SpaceMobile", nameZh: "AST 太空移动", primaryLayer: 2, secondaryLayers: [], narratives: ["space-infrastructure"], role: "narrative spillover", thesis: "卫星直连普通手机的 5G 网络; 颠覆电信叙事弹性筹码。" },
  { ticker: "RDW", name: "Redwire", nameZh: "Redwire", primaryLayer: 2, secondaryLayers: [7], narratives: ["space-infrastructure", "defense-autonomy"], role: "second-order beneficiary", thesis: "在轨制造与航天基础设施供应商; 商业航天工具铲。" },
  // 生物 AI
  { ticker: "SDGR", name: "Schrödinger", nameZh: "薛定谔 (科技)", primaryLayer: 3, secondaryLayers: [2], narratives: ["ai-agents", "financial-data-intelligence"], role: "narrative spillover", thesis: "物理基化学软件平台 + 自研管线, B1 验证仓; 生物 AI 龙头。" },
  { ticker: "RXRX", name: "Recursion Pharma", nameZh: "Recursion 制药", primaryLayer: 2, secondaryLayers: [3], narratives: ["ai-agents"], role: "narrative spillover", thesis: "AI 驱动药物发现平台, 与 NVDA 合作图像基础模型。" },
  { ticker: "TWST", name: "Twist Bioscience", nameZh: "Twist 生物科技", primaryLayer: 5, secondaryLayers: [2], narratives: ["automated-production"], role: "second-order beneficiary", thesis: "合成 DNA / 抗体库, AI 设计后端制造铲。" },
  { ticker: "SANA", name: "Sana Biotechnology", nameZh: "Sana 生物科技", primaryLayer: 1, secondaryLayers: [2], narratives: ["ai-agents"], role: "narrative spillover", thesis: "细胞工程 / 通用 CAR-T 平台, 高弹性长周期赌注。" },
  // 量子计算
  { ticker: "IONQ", name: "IonQ", nameZh: "IonQ 量子", primaryLayer: 1, secondaryLayers: [4], narratives: ["ai-agents"], role: "narrative spillover", thesis: "离子阱量子计算龙头, 替代算力范式赌注。" },
  { ticker: "RGTI", name: "Rigetti Computing", nameZh: "Rigetti 计算", primaryLayer: 1, secondaryLayers: [4], narratives: ["ai-agents"], role: "narrative spillover", thesis: "超导量子比特路线弹性筹码, 高波动量子主题。" },
  { ticker: "QUBT", name: "Quantum Computing", nameZh: "量子计算", primaryLayer: 1, secondaryLayers: [], narratives: ["ai-agents"], role: "narrative spillover", thesis: "光子量子计算高波动叙事股, 量子主题贝塔。" },
  // 量子安全
  { ticker: "LAES", name: "SEALSQ", nameZh: "SEALSQ", primaryLayer: 3, secondaryLayers: [7], narratives: ["financial-data-intelligence", "defense-autonomy"], role: "narrative spillover", thesis: "后量子加密芯片 / 安全 IC 弹性标的, 量子破解防御主题。" },
  // 储能
  { ticker: "FLNC", name: "Fluence Energy", nameZh: "Fluence 储能", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "second-order beneficiary", thesis: "电网级储能系统集成龙头, 可再生 + AI 数据中心配套。" },
  { ticker: "STEM", name: "Stem Inc", nameZh: "Stem", primaryLayer: 6, secondaryLayers: [3], narratives: ["energy-reconstruction"], role: "narrative spillover", thesis: "AI 驱动智能储能软件 + 服务弹性标的。" },
  { ticker: "MVST", name: "Microvast", nameZh: "微宏动力", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction", "automated-production"], role: "narrative spillover", thesis: "商用车快充电池弹性筹码, 储能产业链下游铲。" },
  // 光科技 (硅光 / CPO / 光模块)
  { ticker: "COHR", name: "Coherent", nameZh: "Coherent 相干", primaryLayer: 4, secondaryLayers: [5], narratives: ["ai-agents"], role: "core dependency", thesis: "光模块 + 激光器龙头, 800G/1.6T 数据中心互联核心。" },
  { ticker: "LITE", name: "Lumentum", nameZh: "Lumentum", primaryLayer: 4, secondaryLayers: [5], narratives: ["ai-agents"], role: "core dependency", thesis: "硅光器件 / 高速光模块龙头, AI 集群带宽刚需。" },
  { ticker: "FN", name: "Fabrinet", nameZh: "Fabrinet", primaryLayer: 4, secondaryLayers: [5], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "光模块代工厂, NVDA 互联生态间接受益。" },
  { ticker: "AAOI", name: "Applied Optoelectronics", nameZh: "应用光电", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "narrative spillover", thesis: "光模块上市观察弹性, 数据中心 + 电信 dual exposure。" },
  { ticker: "POET", name: "POET Technologies", nameZh: "POET 科技", primaryLayer: 4, secondaryLayers: [5], narratives: ["ai-agents"], role: "narrative spillover", thesis: "硅光集成平台弹性赌注, CPO (co-packaged optics) 主题。" },
  // === 2026-05-02 新增 ===
  { ticker: "UBER", name: "Uber Technologies", nameZh: "优步", primaryLayer: 2, secondaryLayers: [3], narratives: ["automated-production","ai-agents"], role: "narrative spillover", thesis: "全球出行平台 + Robotaxi 部署网络, Waymo/Tesla autonomy 商业化通路。" },
  { ticker: "SHOP", name: "Shopify", nameZh: "Shopify (购物派)", primaryLayer: 2, secondaryLayers: [3], narratives: ["ai-agents","financial-data-intelligence"], role: "second-order beneficiary", thesis: "电商基础设施 + AI agent 自动建店、定价、客服浪潮直接受益。" },
  { ticker: "NFLX", name: "Netflix", nameZh: "网飞", primaryLayer: 2, secondaryLayers: [3], narratives: ["ai-agents"], role: "narrative spillover", thesis: "AI 生成式内容 + 个性化算法二阶受益, 流媒体长期 stickiness 标的。" },
  { ticker: "ZS", name: "Zscaler", nameZh: "Zscaler 卓尔", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence","defense-autonomy"], role: "constraint variable", thesis: "零信任云安全龙头, AI/agent 流量爆炸放大攻击面。" },
  { ticker: "OKTA", name: "Okta", nameZh: "Okta 身份", primaryLayer: 3, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "second-order beneficiary", thesis: "身份治理层, agent 经济需要机器身份新范式。" },
  { ticker: "TEAM", name: "Atlassian", nameZh: "Atlassian (亚特拉斯团队)", primaryLayer: 3, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "Jira/Confluence 工作流, AI 协作浪潮二阶受益。" },
  { ticker: "HUBS", name: "HubSpot", nameZh: "HubSpot", primaryLayer: 3, secondaryLayers: [2], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "中小企业 CRM + AI agent, copilot for marketing/sales。" },
  { ticker: "INTC", name: "Intel", nameZh: "英特尔", primaryLayer: 4, secondaryLayers: [5], narratives: ["ai-agents"], role: "constraint variable", thesis: "x86 老牌制造 + IDM 2.0 转型, 美政府 CHIPS Act 重押对象。" },
  { ticker: "WDC", name: "Western Digital", nameZh: "西部数据", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "constraint variable", thesis: "硬盘 + NAND 存储, AI 数据爆炸下游受益。" },
  { ticker: "STX", name: "Seagate", nameZh: "希捷", primaryLayer: 4, secondaryLayers: [], narratives: ["ai-agents"], role: "second-order beneficiary", thesis: "高容量 HDD + HAMR 技术, 数据中心冷存储刚需。" },
  { ticker: "TER", name: "Teradyne", nameZh: "泰瑞达", primaryLayer: 5, secondaryLayers: [4], narratives: ["ai-agents","automated-production"], role: "second-order beneficiary", thesis: "半导体测试设备 + 协作机器人 (UR), 双引擎。" },
  { ticker: "NEE", name: "NextEra Energy", nameZh: "新时代能源", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "core dependency", thesis: "美国最大可再生 + 受规公用事业, 数据中心电力刚需。" },
  { ticker: "ENPH", name: "Enphase Energy", nameZh: "Enphase 储能", primaryLayer: 6, secondaryLayers: [], narratives: ["energy-reconstruction"], role: "second-order beneficiary", thesis: "微逆变器 + 储能, 户用太阳能 + AI 优化设备。" },
  { ticker: "USAR", name: "USA Rare Earth", nameZh: "美国稀土", primaryLayer: 6, secondaryLayers: [7], narratives: ["energy-reconstruction","defense-autonomy"], role: "constraint variable", thesis: "美国本土稀土供应弹性筹码, 国防 + 电动化关键约束。" },
  { ticker: "BLK", name: "BlackRock", nameZh: "贝莱德", primaryLayer: 7, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "core dependency", thesis: "全球最大资管, 资本流向定价权 + Aladdin 风险系统。" },
  { ticker: "MS", name: "Morgan Stanley", nameZh: "摩根士丹利", primaryLayer: 7, secondaryLayers: [], narratives: ["financial-data-intelligence"], role: "second-order beneficiary", thesis: "财富管理 + 投行, AI 应用最早的金融机构之一。" },
  { ticker: "GD", name: "General Dynamics", nameZh: "通用动力", primaryLayer: 7, secondaryLayers: [], narratives: ["defense-autonomy"], role: "core dependency", thesis: "潜艇 + 装甲车 + 信息系统, 美军核心 prime。" },
  { ticker: "HII", name: "Huntington Ingalls", nameZh: "亨廷顿英格尔", primaryLayer: 7, secondaryLayers: [], narratives: ["defense-autonomy"], role: "core dependency", thesis: "美国最大军舰建造商, 海军 30 年扩军周期受益。" },
  { ticker: "AXON", name: "Axon Enterprise", nameZh: "Axon (前 TASER)", primaryLayer: 7, secondaryLayers: [3], narratives: ["defense-autonomy","financial-data-intelligence"], role: "second-order beneficiary", thesis: "执法 SaaS + 装备 + AI 视频分析三件套, 政府订阅护城河。" },
  { ticker: "CRSP", name: "CRISPR Therapeutics", nameZh: "CRISPR 治疗", primaryLayer: 1, secondaryLayers: [2], narratives: ["ai-agents"], role: "narrative spillover", thesis: "基因编辑龙头, Casgevy 已 FDA 批准镰状细胞病; 长寿主题入口。" }
];

export const COMPANY_LINKS: CompanyLink[] = [
  { source: "MSFT", target: "NVDA", strength: "core", role: "depends_on", thesis: "Azure AI demand depends on accelerator supply." },
  { source: "GOOGL", target: "AVGO", strength: "strong", role: "depends_on", thesis: "Custom silicon and networking relationship for AI infrastructure." },
  { source: "AMZN", target: "ANET", strength: "strong", role: "depends_on", thesis: "AWS scale needs high-performance data center networking." },
  { source: "META", target: "NVDA", strength: "strong", role: "depends_on", thesis: "Model training and recommendation systems drive GPU demand." },
  { source: "NVDA", target: "TSM", strength: "core", role: "depends_on", thesis: "Accelerators require advanced foundry capacity." },
  { source: "AMD", target: "TSM", strength: "core", role: "depends_on", thesis: "Advanced CPUs and GPUs rely on external foundry capacity." },
  { source: "TSM", target: "ASML", strength: "core", role: "depends_on", thesis: "Leading-edge nodes require EUV lithography." },
  { source: "TSM", target: "AMAT", strength: "strong", role: "depends_on", thesis: "Capacity expansion needs broad equipment supply." },
  { source: "MU", target: "LRCX", strength: "strong", role: "depends_on", thesis: "HBM and memory cycles pull etch and deposition demand." },
  { source: "AVGO", target: "SNPS", strength: "strong", role: "depends_on", thesis: "Custom silicon complexity depends on EDA tooling." },
  { source: "NVDA", target: "SNPS", strength: "strong", role: "depends_on", thesis: "Chip design scale relies on EDA and verification." },
  { source: "ARM", target: "TSM", strength: "weak", role: "enables", thesis: "Efficient IP connects chip design to advanced manufacturing." },
  { source: "ANET", target: "AVGO", strength: "strong", role: "supplies", thesis: "Networking stacks combine switching systems and merchant silicon." },
  { source: "SMCI", target: "NVDA", strength: "core", role: "depends_on", thesis: "Server demand is levered to available accelerator supply." },
  { source: "DELL", target: "NVDA", strength: "strong", role: "depends_on", thesis: "Enterprise AI servers need GPU supply and reference designs." },
  { source: "ORCL", target: "NVDA", strength: "strong", role: "depends_on", thesis: "Cloud AI capacity turns GPU access into growth." },
  { source: "SNOW", target: "MSFT", strength: "weak", role: "depends_on", thesis: "Enterprise data workloads are distributed through cloud partnerships." },
  { source: "CRM", target: "SNOW", strength: "weak", role: "enables", thesis: "Customer workflows become stronger when linked to data clouds." },
  { source: "NOW", target: "MSFT", strength: "weak", role: "enables", thesis: "Enterprise agent workflows meet Microsoft distribution." },
  { source: "PLTR", target: "LMT", strength: "strong", role: "enables", thesis: "Defense software and prime systems converge around autonomy." },
  { source: "CRWD", target: "PANW", strength: "weak", role: "competes_with", thesis: "Security budgets rotate between endpoint, cloud, and platform approaches." },
  { source: "NET", target: "CRWD", strength: "weak", role: "enables", thesis: "Edge traffic and security telemetry expand the security surface." },
  { source: "CEG", target: "NVDA", strength: "strong", role: "constrains", thesis: "Data center growth runs into power availability." },
  { source: "VST", target: "AMZN", strength: "strong", role: "constrains", thesis: "Hyperscale growth depends on dispatchable power." },
  { source: "ETN", target: "CEG", strength: "strong", role: "enables", thesis: "Electrical equipment connects generation to data center load." },
  { source: "PWR", target: "ETN", strength: "strong", role: "enables", thesis: "Grid construction converts equipment demand into deployed capacity." },
  { source: "CCJ", target: "CEG", strength: "strong", role: "supplies", thesis: "Uranium supply underpins nuclear generation economics." },
  { source: "FCX", target: "ETN", strength: "weak", role: "supplies", thesis: "Copper availability matters for electrification and grid equipment." },
  { source: "GEV", target: "PWR", strength: "weak", role: "enables", thesis: "Grid hardware and construction reinforce the same power rebuild cycle." },
  { source: "JPM", target: "TSLA", strength: "weak", role: "finances", thesis: "Credit and capital markets influence long-duration industrial narratives." },
  { source: "GS", target: "APP", strength: "weak", role: "finances", thesis: "Capital market appetite can amplify software narrative multiples." },
  { source: "LMT", target: "NOC", strength: "strong", role: "enables", thesis: "Prime defense systems overlap in space, missiles, and autonomy." },
  { source: "RTX", target: "BA", strength: "strong", role: "supplies", thesis: "Aerospace and defense supply chains remain tightly coupled." },
  { source: "NOC", target: "PLTR", strength: "strong", role: "depends_on", thesis: "Autonomous defense systems increasingly depend on operational software." },
  { source: "CAT", target: "FCX", strength: "weak", role: "enables", thesis: "Mining and heavy equipment cycles reinforce materials supply." },
  { source: "XOM", target: "TSLA", strength: "weak", role: "hedges", thesis: "Hydrocarbon cash flows hedge energy transition volatility." },
  { source: "NEM", target: "JPM", strength: "weak", role: "hedges", thesis: "Gold can hedge capital stress and currency uncertainty." }
,
  // === 2026-05-02 新增链接 ===
  { source: "GOOGL", target: "NVDA", strength: "core", role: "depends_on", thesis: "Gemini/TPU 之外仍需 H100 弹性算力, 多云对冲。" },
  { source: "ORCL", target: "TSM", strength: "weak", role: "depends_on", thesis: "甲骨文云 AI 容量间接依赖先进制造。" },
  { source: "PLTR", target: "NVDA", strength: "weak", role: "depends_on", thesis: "Foundry/Ontology 大模型推理依赖 GPU 弹性。" },
  { source: "UBER", target: "TSLA", strength: "weak", role: "competes_with", thesis: "Robotaxi 网络 vs 单车智能, autonomy 商业化两条路线。" },
  { source: "UBER", target: "NVDA", strength: "weak", role: "depends_on", thesis: "自动驾驶感知/规划训练依赖 GPU 算力。" },
  { source: "SHOP", target: "AMZN", strength: "strong", role: "competes_with", thesis: "电商平台 vs 中小卖家自建店, AI agent 工具放大替代效应。" },
  { source: "SHOP", target: "GOOGL", strength: "weak", role: "depends_on", thesis: "Shopify 流量很大比例来自 Google 广告 + 搜索。" },
  { source: "NFLX", target: "NVDA", strength: "weak", role: "depends_on", thesis: "推荐系统 + 生成内容训练增加 GPU 用量。" },
  { source: "ZS", target: "PANW", strength: "strong", role: "competes_with", thesis: "云安全龙头 vs 平台化安全, 预算分配竞争。" },
  { source: "ZS", target: "NET", strength: "weak", role: "competes_with", thesis: "零信任接入 vs 边缘安全, 长期重叠。" },
  { source: "OKTA", target: "MSFT", strength: "weak", role: "competes_with", thesis: "Identity 标准战, Entra ID 与 Okta 的协议竞争。" },
  { source: "TEAM", target: "MSFT", strength: "weak", role: "competes_with", thesis: "协作工作流, Atlassian 与 Microsoft 365/Teams 边界拉锯。" },
  { source: "HUBS", target: "CRM", strength: "weak", role: "competes_with", thesis: "中小企业 CRM, HubSpot 上探, Salesforce 下探。" },
  { source: "INTC", target: "ASML", strength: "strong", role: "depends_on", thesis: "Intel 18A/14A 节点同样依赖 EUV/High-NA。" },
  { source: "INTC", target: "AMAT", strength: "strong", role: "depends_on", thesis: "Foundry 重启依赖广泛设备扩张。" },
  { source: "INTC", target: "AMD", strength: "strong", role: "competes_with", thesis: "x86 + 数据中心 CPU 长期对峙。" },
  { source: "WDC", target: "MU", strength: "weak", role: "competes_with", thesis: "NAND 价格联动周期, 存储双寡头。" },
  { source: "STX", target: "WDC", strength: "strong", role: "competes_with", thesis: "HDD 双雄, 数据中心冷存储分蛋糕。" },
  { source: "TER", target: "TSM", strength: "weak", role: "supplies", thesis: "测试设备给到 foundry 装机, AI 芯片测试链刚需。" },
  { source: "NEE", target: "NVDA", strength: "core", role: "constrains", thesis: "AI 数据中心电力扩张 NEE 是首选可再生供应。" },
  { source: "NEE", target: "AMZN", strength: "strong", role: "supplies", thesis: "AWS 长协采购可再生电力, NEE 主力 PPA 方。" },
  { source: "ENPH", target: "TSLA", strength: "weak", role: "competes_with", thesis: "户用储能/逆变器市场 vs Powerwall 生态。" },
  { source: "USAR", target: "TSLA", strength: "weak", role: "supplies", thesis: "稀土供应链美国本土化, 电机磁铁关键。" },
  { source: "USAR", target: "LMT", strength: "weak", role: "supplies", thesis: "国防供应链稀土去风险关键节点。" },
  { source: "BLK", target: "JPM", strength: "weak", role: "competes_with", thesis: "资管 vs 投行, 资本市场两大支柱不同入口。" },
  { source: "MS", target: "GS", strength: "strong", role: "competes_with", thesis: "投行/财富管理双雄。" },
  { source: "BLK", target: "GEV", strength: "weak", role: "finances", thesis: "气候/基建主题 ETF 间接配置 GE Vernova。" },
  { source: "GD", target: "HII", strength: "strong", role: "competes_with", thesis: "潜艇/海军船厂分蛋糕, 弹性互补。" },
  { source: "GD", target: "LMT", strength: "weak", role: "competes_with", thesis: "国防 prime 间互相补位且竞标。" },
  { source: "AXON", target: "PLTR", strength: "weak", role: "competes_with", thesis: "执法 + 政府数据化, 应用堆叠重叠。" },
  { source: "HII", target: "RTX", strength: "strong", role: "depends_on", thesis: "舰艇平台依赖雷神导弹/雷达。" },
  { source: "CRSP", target: "TWST", strength: "weak", role: "depends_on", thesis: "基因编辑实验依赖合成 DNA 材料。" },
  { source: "IONQ", target: "TSM", strength: "weak", role: "depends_on", thesis: "量子计算硬件部分组件来自先进 foundry。" },
  { source: "RXRX", target: "NVDA", strength: "strong", role: "depends_on", thesis: "图像基础模型与 NVDA BioNeMo 合作。" },
  { source: "SDGR", target: "NVDA", strength: "weak", role: "depends_on", thesis: "化学模拟 + 折叠模型加速 GPU 算力。" }
];
